<?php

defined( 'ABSPATH' ) || exit;

/**
 * Minimal TS Pay HTTP client.
 */
class EDD_TSPay_API {
	/** @var string */
	private $base_url;

	/** @var string */
	private $api_key;

	/** @var int */
	private $timeout;

	/**
	 * @param string|null $base_url Optional API URL override.
	 * @param string|null $api_key  Optional API key override.
	 */
	public function __construct( $base_url = null, $api_key = null ) {
		$is_test        = function_exists( 'edd_is_test_mode' ) && edd_is_test_mode();
		$default_url    = $is_test ? 'https://api-staging.tspay.app' : 'https://api.tspay.app';
		$configured_url = edd_get_option( $is_test ? 'tspay_test_api_url' : 'tspay_live_api_url', $default_url );
		$configured_key = edd_get_option( $is_test ? 'tspay_test_api_key' : 'tspay_live_api_key', '' );

		$this->base_url = untrailingslashit( $base_url ?: $configured_url );
		$this->api_key  = trim( (string) ( null === $api_key ? $configured_key : $api_key ) );
		$this->timeout  = max( 5, min( 60, absint( edd_get_option( 'tspay_api_timeout', 20 ) ) ) );
	}

	/**
	 * Check the active API key.
	 *
	 * @return array|WP_Error
	 */
	public function authenticate() {
		return $this->request( 'GET', '/auth/' );
	}

	/**
	 * Create a LinkToPay order.
	 *
	 * @param array $payload Request body.
	 * @return array|WP_Error
	 */
	public function create_link_to_pay( array $payload ) {
		return $this->request( 'POST', '/orders/link2pay', $payload );
	}

	/**
	 * Retrieve charges generated by an order.
	 *
	 * @param string $order_key TS Pay order key.
	 * @return array|WP_Error
	 */
	public function get_charges_for_order( $order_key ) {
		return $this->request( 'GET', '/charges/orders/' . rawurlencode( $order_key ) );
	}

	/**
	 * Send an authenticated JSON request.
	 *
	 * @param string     $method  HTTP method.
	 * @param string     $path    Absolute API path.
	 * @param array|null $payload Optional JSON body.
	 * @return array|WP_Error
	 */
	public function request( $method, $path, $payload = null ) {
		if ( empty( $this->base_url ) || ! self::valid_http_url( $this->base_url ) ) {
			return new WP_Error( 'tspay_invalid_api_url', __( 'L’URL API TS Pay non è valida.', 'edd-tspay' ) );
		}

		if ( empty( $this->api_key ) ) {
			return new WP_Error( 'tspay_missing_api_key', __( 'La API key TS Pay non è configurata.', 'edd-tspay' ) );
		}

		$args = array(
			'method'      => strtoupper( $method ),
			'timeout'     => $this->timeout,
			'redirection' => 0,
			'headers'     => array(
				'Authorization' => 'Bearer ' . $this->api_key,
				'Accept'        => 'application/json',
				'Content-Type'  => 'application/json; charset=utf-8',
				'User-Agent'    => 'EDD-TS-Pay/' . EDD_TSPAY_VERSION . '; ' . home_url( '/' ),
			),
		);

		if ( null !== $payload ) {
			$args['body'] = wp_json_encode( $payload );
		}

		$response = wp_remote_request( $this->base_url . '/' . ltrim( $path, '/' ), $args );

		if ( is_wp_error( $response ) ) {
			return new WP_Error( 'tspay_transport_error', __( 'TS Pay non è raggiungibile.', 'edd-tspay' ), $response->get_error_message() );
		}

		$status = (int) wp_remote_retrieve_response_code( $response );
		$body   = (string) wp_remote_retrieve_body( $response );
		$data   = '' === $body ? array() : json_decode( $body, true );

		if ( JSON_ERROR_NONE !== json_last_error() ) {
			return new WP_Error( 'tspay_invalid_json', __( 'TS Pay ha restituito una risposta non valida.', 'edd-tspay' ), array( 'status' => $status ) );
		}

		if ( $status < 200 || $status >= 300 ) {
			$message = is_array( $data ) && ! empty( $data['message'] ) ? sanitize_text_field( $data['message'] ) : __( 'Richiesta TS Pay rifiutata.', 'edd-tspay' );
			return new WP_Error( 'tspay_http_error', $message, array( 'status' => $status, 'response' => $data ) );
		}

		return is_array( $data ) ? $data : array();
	}

	/** @return bool */
	private static function valid_http_url( $url ) {
		$parts = wp_parse_url( $url );
		return is_array( $parts ) && ! empty( $parts['host'] ) && ! empty( $parts['scheme'] ) && in_array( strtolower( $parts['scheme'] ), array( 'http', 'https' ), true );
	}
}
